spring.application.name=ProductServicev1
server.port=8901

# MongoDB Docker connection
#spring.mongodb.uri=mongodb://root:1234@localhost:27018/productdb?authSource=admin


# MongoDB Docker connection
spring.mongodb.uri=mongodb://root:1234@localhost:27018/productdb?authSource=admin